name: dolphin-emulator
base: core
version: '5.0'
summary: A Wii/GameCube Emulator
description: |
  Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii. 
  It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with 
  several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer, and even more.
license: GPL-2.0
icon: snap/gui/dolphin-emu.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
parts:
  dolphin-emu:
    plugin: cmake
    # cmake-parameters:
    configflags:
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DCMAKE_INSTALL_PREFIX=/usr/local"
    - "-DLINUX_LOCAL_DEV=TRUE"
    - "-DENABLE_SDL=ON"
    source: https://github.com/dolphin-emu/dolphin.git
    source-tag: '5.0'
    build-packages:
      - build-essential
      - ffmpeg 
      - libavcodec-dev
      - libevdev-dev
      - libusb-1.0-0-dev
      - libavformat-dev
      - libswscale-dev
      - libwxbase3.0-dev
      - libwxgtk3.0-dev
      - libsdl2-dev
      - libsfml-dev
      - libminiupnpc-dev
      - libmbedtls-dev
      - libhidapi-dev
      - libpulse-dev
      - libpangocairo-1.0-0
      - libgtk2.0-dev
      - libbluetooth-dev
      - qt5-default
      - qtbase5-private-dev
      - qtbase5-dev
      - libudev-dev
    # Stage packages for core18
    # stage-packages:
    #   - libusb-1.0-0
    #   - ffmpeg
    #   - libavcodec57
    #   - libhidapi-dev
    #   - libsfml-audio2.4
    #   - libsfml-graphics2.4
    #   - libsfml-network2.4
    #   - libsfml-system2.4
    #   - libsfml-window2.4
    #   - libmbedtls10
    #   - libminiupnpc10
    #   - libavformat57
    #   - libbluetooth3
    #   - libpulse0
    #   - libgtk2.0-0
    #   - libwxgtk3.0-0v5
    #   - libwxbase3.0-0v5
    #   - libswscale4
    #   - libslang2
    #   - libevdev2
    #   - libglu1-mesa
    #   - libsdl2-2.0-0
    #   - liburi-encode-perl
    #   # Are all the below needed?
    #   - libgl1-mesa-dri
    #   - libxcb-xinerama0
    #   - libxinerama1
    #   - libpangocairo-1.0-0
    #   - libudev1
    #   - libcanberra-gtk-module
    #   # - libvulkan1
    #   # - mesa-vulkan-drivers
    #   # - nvidia-driver-440 # seems to fix nvidia vulkan at the cost of adding 100MB+ to final package, may be able to cleanup unecessary files?
    #   # - vulkan-utils
    #   - libbluray2
    #   - xdg-utils
    #   - freeglut3
    stage-packages:
      - libusb-1.0-0
      - ffmpeg
      - libavcodec-ffmpeg56
      - libhidapi-dev
      - libsfml-audio2.3v5
      - libsfml-graphics2.3v5
      - libsfml-network2.3v5
      - libsfml-system2.3v5
      - libsfml-window2.3v5
      - libmbedtls10
      - libminiupnpc10
      - libavformat-ffmpeg56
      - libbluetooth3
      - libpulse0
      - libgtk2.0-0
      - libwxgtk3.0-0v5
      - libwxbase3.0-0v5
      - libswscale-ffmpeg3
      - libslang2
      - libevdev2
      - libglu1-mesa
      - libsdl2-2.0-0
      - liburi-encode-perl
      # Are all the below needed?
      - libgl1-mesa-dri
      - libxcb-xinerama0
      - libxinerama1
      - libpangocairo-1.0-0
      - libudev1
      - libcanberra-gtk-module
      - libbluray1
      - xdg-utils
      - freeglut3
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/5.0/reformatxgetbv.patch
      git apply $SNAPCRAFT_STAGE/5.0/sharedmemory.patch
      git apply $SNAPCRAFT_STAGE/5.0/rasterfontconstnames.patch
      git apply $SNAPCRAFT_STAGE/5.0/removedirtyversion.patch
      # git apply $SNAPCRAFT_STAGE/forcexdg.patch
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=dolphin-emu|Icon=/usr/local/share/icons/hicolor/scalable/apps/dolphin-emu.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop
      sed -i 's|Exec=env QT_QPA_PLATFORM=xcb dolphin-emu|Exec=dolphin-emu|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop
    organize: 
        #Copy Sys folder to the Binaries folder
        usr/local/share/dolphin-emu/sys: usr/local/bin/Sys
    after:
      - patches
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - locales-all
      - xdg-user-dirs
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME=$SNAP_USER_DATA|XDG_DATA_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
      sed -i 's|XDG_CONFIG_HOME=$SNAP_USER_DATA|XDG_CONFIG_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
  patches:
    plugin: dump
    source: snap/local/patches
    source-type: local
    prime:
      - -*
  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
  #
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - dolphin-emu
      - patches
      - desktop-qt5
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core
      # - kde-frameworks-5-core18
    override-prime: |
      set -eux
      # for snap in "core18" "kde-frameworks-5-core18" "kde-frameworks-5-core18-sdk"; do  # List all content-snaps and base snaps you're using here
      for snap in "core"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  # gtk-2-themes:
  #   interface: content
  #   target: $SNAP/data-dir/themes
  #   default-provider: gtk-common-themes:gtk-2-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libGLX_nvidia.so.0

apps:
  dolphin-emu:
    command: bin/desktop-launch $SNAP/usr/local/bin/dolphin-emu
    desktop: usr/local/share/applications/dolphin-emu.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      KDE_FORK_SLAVES: 1
      DISABLE_WAYLAND: 1
      # KF5_LIBEXEC_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
      PATH: "$PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5" # Allows kioslave5 to be found, above commented env variable doesn't work for some reason  
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - opengl
      - joystick
      - unity7
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
      - bluetooth-control
      # - bluez
  dolphin-emu-nogui:
    command: usr/local/bin/dolphin-emu-nogui
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - opengl
      - joystick
      - unity7
      - network
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe


