name: dolphin-emulator
base: core18
version: '5.0'
summary: A Wii/GameCube Emulator
description: |
  Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii.
  It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with
  several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer,
  and even more.
  
  This snap is not necessarily endorsed or officially maintained by the upstream developers.
  
  Upstream Project: https://dolphin-emu.org/ snapcraft.yaml Build Definition:
  https://github.com/Nightmayr-snaps/dolphin-snap
license: GPL-2.0
icon: snap/gui/dolphin-emu.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64
parts:
  dolphin-emu:
    plugin: cmake
    configflags:
    - "-DCMAKE_BUILD_TYPE=Release"
    - "-DCMAKE_INSTALL_PREFIX=/usr/local"
    - "-DLINUX_LOCAL_DEV=TRUE"
    - "-DENABLE_SDL=ON"
    source: https://github.com/dolphin-emu/dolphin.git
    source-tag: '5.0'
    build-packages:
      - build-essential
      - ffmpeg 
      - libavcodec-dev
      - libevdev-dev
      - libusb-1.0-0-dev
      - libavformat-dev
      - libswscale-dev
      - libwxbase3.0-dev
      - libwxgtk3.0-gtk3-dev
      - libsdl2-dev
      - libsfml-dev
      - libminiupnpc-dev
      - libmbedtls-dev
      - libhidapi-dev
      - libpulse-dev
      - libpangocairo-1.0-0
      - libgtk-3-dev
      - libgdk-pixbuf2.0-dev
      - libbluetooth-dev
      - libudev-dev
    stage-packages:
      - libusb-1.0-0
      - ffmpeg
      - libavcodec57
      - libhidapi-dev
      - libsfml-audio2.4
      - libsfml-graphics2.4
      - libsfml-network2.4
      - libsfml-system2.4
      - libsfml-window2.4
      - libmbedtls10
      - libminiupnpc10
      - libavformat57
      - libbluetooth3
      - libpulse0
      - libwxgtk3.0-gtk3-0v5
      - libwxbase3.0-0v5
      - libswscale4
      - libslang2
      - libevdev2
      - libglu1-mesa
      - libsdl2-2.0-0
      - liburi-encode-perl
      - libgl1-mesa-dri
      - libudev1
      - libbluray2
      - xdg-utils
      - freeglut3
      - libnet-dbus-perl
      - libx11-protocol-perl
      # - x11-xserver-utils
      - libglib2.0-bin
      - gettext
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/5.0/reformatxgetbv.patch
      git apply $SNAPCRAFT_STAGE/5.0/sharedmemory.patch
      git apply $SNAPCRAFT_STAGE/5.0/rasterfontconstnames.patch
      git apply $SNAPCRAFT_STAGE/5.0/removedirtyversion.patch
      git apply $SNAPCRAFT_STAGE/5.0/gtk3.patch
      git apply $SNAPCRAFT_STAGE/5.0/nopie.patch
    override-build: |
      apt remove libasound2 -y
      snapcraftctl build
      sed -i 's|Icon=dolphin-emu|Icon=/usr/local/share/icons/hicolor/scalable/apps/dolphin-emu.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop
      sed -i 's|Exec=env QT_QPA_PLATFORM=xcb dolphin-emu|Exec=dolphin-emu|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop
    organize: 
        #Copy Sys folder to the Binaries folder
        usr/local/share/dolphin-emu/sys: usr/local/bin/Sys
    after:
      - patches
      # - desktop-packages
      - desktop-qt5
  desktop-qt5:
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    make-parameters:
    - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgdk-pixbuf2.0-0
    - locales-all
    - xdg-user-dirs
    - libgtk2.0-0
    - xdg-utils
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME=$SNAP_USER_DATA|XDG_DATA_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
      sed -i 's|XDG_CONFIG_HOME=$SNAP_USER_DATA|XDG_CONFIG_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
  # desktop-packages:
  #   plugin: nil
  #   stage-packages:
  #     - libgdk-pixbuf2.0-0
  #     - adwaita-icon-theme
  #     - gnome-themes-standard
  #     - shared-mime-info
  #     - libxkbcommon0
  #     - ttf-ubuntu-font-family
  #     - dmz-cursor-theme
  #     - light-themes
  #     - locales-all
  #     - xdg-user-dirs
  #     - libgtk2.0-0
  patches:
    plugin: dump
    source: snap/local/patches
    source-type: local
    prime:
      - -*
  launchers:
    plugin: dump
    source: snap/local/launchers
    source-type: local
    organize:
      '*': bin/
  # This part removes all the files in this snap which already exist in
  # connected content and base snaps. Since these files will be available
  # at runtime from the content and base snaps, they do not need to be
  # included in this snap itself.
  #
  # More info: https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html 
  # #
  # cleanup:
  #   after:  # Make this part run last; list all your other parts here
  #     - dolphin-emu
  #     - patches
  #     - desktop-packages
  #   plugin: nil
  #   build-snaps:  # List all content-snaps and base snaps you're using here
  #     - core18
  #   override-prime: |
  #     set -eux
  #     for snap in "core18"; do  # List all content-snaps and base snaps you're using here
  #       cd "/snap/$snap/current" && find . -type f -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
  #     done

layout:
    /usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.26.1:
      symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl/5.26.1
    /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.26:
      symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/perl5/5.26
    /usr/share/perl5/XML:
      symlink: $SNAP/usr/share/perl5/XML
    /usr/share/perl/5.26:
      symlink: $SNAP/usr/share/perl/5.26.1
    /usr/share/perl5/X11:
      symlink: $SNAP/usr/share/perl5/X11

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  dolphin-emu:
    command: usr/local/bin/dolphin-emu
    command-chain:
      # - bin/dolphin-launch
      - bin/desktop-launch
    desktop: usr/local/share/applications/dolphin-emu.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - audio-playback
      - opengl
      - joystick
      - unity7
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
      - bluez
      - optical-drive
      - raw-usb
  dolphin-emu-nogui:
    command: usr/local/bin/dolphin-emu-nogui
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - x11
      - wayland
      - audio-playback
      - opengl
      - joystick
      - unity7
      - network
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
      - bluez
      - optical-drive
      - raw-usb

