name: dolphin-emulator
base: core20
version: '5.0'
summary: A Wii/GameCube Emulator
description: |
  Dolphin is an emulator for two recent Nintendo video game consoles: the GameCube and the Wii. 
  It allows PC gamers to enjoy games for these two consoles in full HD (1080p) with 
  several enhancements: compatibility with all PC controllers, turbo speed, networked multiplayer, and even more.
license: GPL-2.0
icon: snap/gui/dolphin-emu.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
parts:
  dolphin-emu:
    plugin: cmake
    source: https://github.com/dolphin-emu/dolphin.git
    source-commit: 9c12a843f86d39bc64d9e9b5b670e67455487739
    build-packages:
      - ffmpeg 
      - libavcodec-dev
      - libevdev-dev
      - libusb-1.0-0-dev
      - libavformat-dev
      - libswscale-dev
      - libsfml-dev
      - libminiupnpc-dev
      - libmbedtls-dev
      - libhidapi-dev
      - libpangocairo-1.0-0
      - libgtk2.0-dev
      - libbluetooth-dev
      - qt5-default
      - qtbase5-private-dev
      - qtbase5-dev
      - libudev-dev
    stage-packages:
      - libusb-1.0-0-dev
      - ffmpeg
      - libavcodec-dev
      - libhidapi-dev
      - libsfml-dev
      - libmbedtls-dev
      - libminiupnpc-dev
      - libavformat-dev
      - libbluetooth-dev
      - freeglut3
      - libglu1
      - libpulse0
      # Are all the below needed?
      - libgtk2.0-dev
      - libpulse-dev
      - libgl1-mesa-dev
      - libswscale-dev
      - libwxbase3.0-dev
      - libwxgtk3.0-gtk3-dev
      - libpangocairo-1.0-0
      - libudev-dev
    override-pull: |
      snapcraftctl pull
      git apply $SNAPCRAFT_STAGE/shared-memory.patch
      git apply $SNAPCRAFT_STAGE/nodirtyversion.patch
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=dolphin-emu|Icon=/usr/local/share/icons/hicolor/scalable/apps/dolphin-emu.svg|' $SNAPCRAFT_PART_INSTALL/usr/local/share/applications/dolphin-emu.desktop
    after:
      - patches
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try:
          - appmenu-qt5
      - locales-all
      - xdg-user-dirs
      - libgtk2.0-0
      - qt5-gtk-platformtheme
      # Are all the below needed?
      - libqt5multimedia5-plugins
      - qtmultimedia5-dev
      - qtwayland5
    override-prime: |
      snapcraftctl prime
      sed -i 's|XDG_DATA_HOME=$SNAP_USER_DATA|XDG_DATA_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
      sed -i 's|XDG_CONFIG_HOME=$SNAP_USER_DATA|XDG_CONFIG_HOME=$SNAP_USER_COMMON|' $SNAPCRAFT_PRIME/bin/desktop-launch
  plasma-integration:
    plugin: nil
    stage-packages:
      - breeze-icon-theme
      - kde-style-breeze
      - plasma-integration
  patches:
    plugin: dump
    source: snap/local/patches
    source-type: local
    prime:
      - -*

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-2-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

apps:
  dolphin-emu:
    command: bin/desktop-launch $SNAP/usr/local/bin/dolphin-emu
    desktop: usr/local/share/applications/dolphin-emu.desktop
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      KDE_FORK_SLAVES: 1
      DISABLE_WAYLAND: 1
      # KF5_LIBEXEC_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5"
      PATH: "$PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libexec/kf5" # Allows kioslave5 to be found, above commented env variable doesn't work for some reason  
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - pulseaudio
      - opengl
      - joystick
      - unity7
      - network
      - network-bind
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe
      - bluetooth-control
      # - bluez
  dolphin-emu-nogui:
    command: usr/local/bin/dolphin-emu-nogui
    environment:
      HOME: "$SNAP_USER_COMMON"
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - pulseaudio
      - opengl
      - joystick
      - unity7
      - network
      - home
      - removable-media
      - gsettings
      - hardware-observe
      - mount-observe


