name: Rebuild Snap

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Snap channel to rebuild'     
        required: true
        default: 'stable'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print channel
      run: |
        echo "channel: ${{ github.event.inputs.channel }}"
    - uses: actions/checkout@v2
      if: ${{ github.event.inputs.channel }} == 'stable'
      with:
        token: ${{ secrets.PAT }}
        ref: master
    - uses: actions/checkout@v2
      if: ${{ github.event.inputs.channel }} != 'stable'
      with:
        token: ${{ secrets.PAT }}
        ref: ${{ github.event.inputs.channel }}
    - uses: snapcore/action-build@v1.1.0
      id: snapcraft
    # - name: Testing snap
    #   run: |
    #     sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    #     snap run dolphin-emulator.dolphin-emu --version
    - uses: snapcore/action-publish@v1.1.1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: ${{ github.event.inputs.channel }}