name: Build-Snap-Stable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ secrets.PAT }}
    - uses: snapcore/action-build@v1.1.0
      id: snapcraft
    # - name: Testing snap
    #   run: |
    #     sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
    #     snap run dolphin-emulator.dolphin-emu-nogui --version
    - uses: snapcore/action-publish@v1.1.1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: candidate
